package com.project.convertedCode.globalNamespace.namespaces.SebastianBergmann.namespaces.ResourceOperations.classes;

import com.runtimeconverter.runtime.passByReference.PassByReferenceArgs;
import com.runtimeconverter.runtime.classes.StaticBaseClass;
import com.runtimeconverter.runtime.classes.RuntimeClassBase;
import com.runtimeconverter.runtime.RuntimeEnv;
import com.runtimeconverter.runtime.annotations.ConvertedMethod;
import com.runtimeconverter.runtime.ZVal;
import com.runtimeconverter.runtime.reflection.ReflectionClassData;
import com.runtimeconverter.runtime.arrays.ZPair;

/*

 Converted with The Runtime Converter (runtimeconverter.com)

 vendor/sebastian/resource-operations/src/ResourceOperations.php

*/

public class ResourceOperations extends RuntimeClassBase {

    public ResourceOperations(RuntimeEnv env, Object... args) {
        super(env);
    }

    public static final Object CONST_class =
            "SebastianBergmann\\ResourceOperations\\ResourceOperations";

    // Runtime Converter Internals
    // RuntimeStaticCompanion contains static methods
    // RequestStaticProperties contains static (per-request) properties
    // ReflectionClassData contains php reflection data used by the runtime library

    public static class RuntimeStaticCompanion extends StaticBaseClass {

        @ConvertedMethod
        public Object getFunctions(RuntimeEnv env, Object... args) {
            return ZVal.assign(
                    ZVal.newArray(
                            new ZPair(0, "Directory::close"),
                            new ZPair(1, "Directory::read"),
                            new ZPair(2, "Directory::rewind"),
                            new ZPair(3, "HttpResponse::getRequestBodyStream"),
                            new ZPair(4, "HttpResponse::getStream"),
                            new ZPair(5, "MongoGridFSCursor::__construct"),
                            new ZPair(6, "MongoGridFSFile::getResource"),
                            new ZPair(7, "MysqlndUhConnection::stmtInit"),
                            new ZPair(8, "MysqlndUhConnection::storeResult"),
                            new ZPair(9, "MysqlndUhConnection::useResult"),
                            new ZPair(10, "PDF_new"),
                            new ZPair(11, "PDO::pgsqlLOBOpen"),
                            new ZPair(12, "RarEntry::getStream"),
                            new ZPair(13, "SQLite3::openBlob"),
                            new ZPair(14, "XMLWriter::openMemory"),
                            new ZPair(15, "XMLWriter::openURI"),
                            new ZPair(16, "ZipArchive::getStream"),
                            new ZPair(17, "bbcode_create"),
                            new ZPair(18, "bzopen"),
                            new ZPair(19, "crack_opendict"),
                            new ZPair(20, "cubrid_connect"),
                            new ZPair(21, "cubrid_connect_with_url"),
                            new ZPair(22, "cubrid_get_query_timeout"),
                            new ZPair(23, "cubrid_lob2_bind"),
                            new ZPair(24, "cubrid_lob2_close"),
                            new ZPair(25, "cubrid_lob2_export"),
                            new ZPair(26, "cubrid_lob2_import"),
                            new ZPair(27, "cubrid_lob2_new"),
                            new ZPair(28, "cubrid_lob2_read"),
                            new ZPair(29, "cubrid_lob2_seek"),
                            new ZPair(30, "cubrid_lob2_seek64"),
                            new ZPair(31, "cubrid_lob2_size"),
                            new ZPair(32, "cubrid_lob2_size64"),
                            new ZPair(33, "cubrid_lob2_tell"),
                            new ZPair(34, "cubrid_lob2_tell64"),
                            new ZPair(35, "cubrid_lob2_write"),
                            new ZPair(36, "cubrid_pconnect"),
                            new ZPair(37, "cubrid_pconnect_with_url"),
                            new ZPair(38, "cubrid_prepare"),
                            new ZPair(39, "cubrid_query"),
                            new ZPair(40, "cubrid_set_query_timeout"),
                            new ZPair(41, "cubrid_unbuffered_query"),
                            new ZPair(42, "curl_copy_handle"),
                            new ZPair(43, "curl_getinfo"),
                            new ZPair(44, "curl_init"),
                            new ZPair(45, "curl_multi_add_handle"),
                            new ZPair(46, "curl_multi_close"),
                            new ZPair(47, "curl_multi_exec"),
                            new ZPair(48, "curl_multi_getcontent"),
                            new ZPair(49, "curl_multi_info_read"),
                            new ZPair(50, "curl_multi_init"),
                            new ZPair(51, "curl_multi_remove_handle"),
                            new ZPair(52, "curl_multi_select"),
                            new ZPair(53, "curl_multi_setopt"),
                            new ZPair(54, "curl_pause"),
                            new ZPair(55, "curl_reset"),
                            new ZPair(56, "curl_setopt"),
                            new ZPair(57, "curl_setopt_array"),
                            new ZPair(58, "curl_share_close"),
                            new ZPair(59, "curl_share_init"),
                            new ZPair(60, "curl_share_setopt"),
                            new ZPair(61, "curl_unescape"),
                            new ZPair(62, "cyrus_connect"),
                            new ZPair(63, "db2_column_privileges"),
                            new ZPair(64, "db2_columns"),
                            new ZPair(65, "db2_connect"),
                            new ZPair(66, "db2_exec"),
                            new ZPair(67, "db2_foreign_keys"),
                            new ZPair(68, "db2_next_result"),
                            new ZPair(69, "db2_pconnect"),
                            new ZPair(70, "db2_prepare"),
                            new ZPair(71, "db2_primary_keys"),
                            new ZPair(72, "db2_procedure_columns"),
                            new ZPair(73, "db2_procedures"),
                            new ZPair(74, "db2_special_columns"),
                            new ZPair(75, "db2_statistics"),
                            new ZPair(76, "db2_table_privileges"),
                            new ZPair(77, "db2_tables"),
                            new ZPair(78, "dba_fetch"),
                            new ZPair(79, "dba_fetch 1"),
                            new ZPair(80, "dba_open"),
                            new ZPair(81, "dba_popen"),
                            new ZPair(82, "dbplus_aql"),
                            new ZPair(83, "dbplus_open"),
                            new ZPair(84, "dbplus_rcreate"),
                            new ZPair(85, "dbplus_ropen"),
                            new ZPair(86, "dbplus_rquery"),
                            new ZPair(87, "dbplus_sql"),
                            new ZPair(88, "deflate_init"),
                            new ZPair(89, "dio_open"),
                            new ZPair(90, "eio_busy"),
                            new ZPair(91, "eio_cancel"),
                            new ZPair(92, "eio_chmod"),
                            new ZPair(93, "eio_chown"),
                            new ZPair(94, "eio_close"),
                            new ZPair(95, "eio_custom"),
                            new ZPair(96, "eio_dup2"),
                            new ZPair(97, "eio_fallocate"),
                            new ZPair(98, "eio_fchmod"),
                            new ZPair(99, "eio_fchown"),
                            new ZPair(100, "eio_fdatasync"),
                            new ZPair(101, "eio_fstat"),
                            new ZPair(102, "eio_fstatvfs"),
                            new ZPair(103, "eio_fsync"),
                            new ZPair(104, "eio_ftruncate"),
                            new ZPair(105, "eio_futime"),
                            new ZPair(106, "eio_get_last_error"),
                            new ZPair(107, "eio_grp"),
                            new ZPair(108, "eio_grp_add"),
                            new ZPair(109, "eio_grp_cancel"),
                            new ZPair(110, "eio_grp_limit"),
                            new ZPair(111, "eio_link"),
                            new ZPair(112, "eio_lstat"),
                            new ZPair(113, "eio_mkdir"),
                            new ZPair(114, "eio_mknod"),
                            new ZPair(115, "eio_nop"),
                            new ZPair(116, "eio_open"),
                            new ZPair(117, "eio_read"),
                            new ZPair(118, "eio_readahead"),
                            new ZPair(119, "eio_readdir"),
                            new ZPair(120, "eio_readlink"),
                            new ZPair(121, "eio_realpath"),
                            new ZPair(122, "eio_rename"),
                            new ZPair(123, "eio_rmdir"),
                            new ZPair(124, "eio_seek"),
                            new ZPair(125, "eio_sendfile"),
                            new ZPair(126, "eio_stat"),
                            new ZPair(127, "eio_statvfs"),
                            new ZPair(128, "eio_symlink"),
                            new ZPair(129, "eio_sync"),
                            new ZPair(130, "eio_sync_file_range"),
                            new ZPair(131, "eio_syncfs"),
                            new ZPair(132, "eio_truncate"),
                            new ZPair(133, "eio_unlink"),
                            new ZPair(134, "eio_utime"),
                            new ZPair(135, "eio_write"),
                            new ZPair(136, "enchant_broker_free_dict"),
                            new ZPair(137, "enchant_broker_init"),
                            new ZPair(138, "enchant_broker_request_dict"),
                            new ZPair(139, "enchant_broker_request_pwl_dict"),
                            new ZPair(140, "event_base_new"),
                            new ZPair(141, "event_base_reinit"),
                            new ZPair(142, "event_buffer_new"),
                            new ZPair(143, "event_new"),
                            new ZPair(144, "event_priority_set"),
                            new ZPair(145, "event_timer_set"),
                            new ZPair(146, "expect_popen"),
                            new ZPair(147, "fam_monitor_collection"),
                            new ZPair(148, "fam_monitor_directory"),
                            new ZPair(149, "fam_monitor_file"),
                            new ZPair(150, "fam_open"),
                            new ZPair(151, "fann_cascadetrain_on_data"),
                            new ZPair(152, "fann_cascadetrain_on_file"),
                            new ZPair(153, "fann_clear_scaling_params"),
                            new ZPair(154, "fann_copy"),
                            new ZPair(155, "fann_create_from_file"),
                            new ZPair(156, "fann_create_shortcut_array"),
                            new ZPair(157, "fann_create_standard"),
                            new ZPair(158, "fann_create_standard_array"),
                            new ZPair(159, "fann_create_train"),
                            new ZPair(160, "fann_create_train_from_callback"),
                            new ZPair(161, "fann_descale_input"),
                            new ZPair(162, "fann_descale_output"),
                            new ZPair(163, "fann_descale_train"),
                            new ZPair(164, "fann_destroy"),
                            new ZPair(165, "fann_destroy_train"),
                            new ZPair(166, "fann_duplicate_train_data"),
                            new ZPair(167, "fann_get_MSE"),
                            new ZPair(168, "fann_get_activation_function"),
                            new ZPair(169, "fann_get_activation_steepness"),
                            new ZPair(170, "fann_get_bias_array"),
                            new ZPair(171, "fann_get_bit_fail"),
                            new ZPair(172, "fann_get_bit_fail_limit"),
                            new ZPair(173, "fann_get_cascade_activation_functions"),
                            new ZPair(174, "fann_get_cascade_activation_functions_count"),
                            new ZPair(175, "fann_get_cascade_activation_steepnesses"),
                            new ZPair(176, "fann_get_cascade_activation_steepnesses_count"),
                            new ZPair(177, "fann_get_cascade_candidate_change_fraction"),
                            new ZPair(178, "fann_get_cascade_candidate_limit"),
                            new ZPair(179, "fann_get_cascade_candidate_stagnation_epochs"),
                            new ZPair(180, "fann_get_cascade_max_cand_epochs"),
                            new ZPair(181, "fann_get_cascade_max_out_epochs"),
                            new ZPair(182, "fann_get_cascade_min_cand_epochs"),
                            new ZPair(183, "fann_get_cascade_min_out_epochs"),
                            new ZPair(184, "fann_get_cascade_num_candidate_groups"),
                            new ZPair(185, "fann_get_cascade_num_candidates"),
                            new ZPair(186, "fann_get_cascade_output_change_fraction"),
                            new ZPair(187, "fann_get_cascade_output_stagnation_epochs"),
                            new ZPair(188, "fann_get_cascade_weight_multiplier"),
                            new ZPair(189, "fann_get_connection_array"),
                            new ZPair(190, "fann_get_connection_rate"),
                            new ZPair(191, "fann_get_errno"),
                            new ZPair(192, "fann_get_errstr"),
                            new ZPair(193, "fann_get_layer_array"),
                            new ZPair(194, "fann_get_learning_momentum"),
                            new ZPair(195, "fann_get_learning_rate"),
                            new ZPair(196, "fann_get_network_type"),
                            new ZPair(197, "fann_get_num_input"),
                            new ZPair(198, "fann_get_num_layers"),
                            new ZPair(199, "fann_get_num_output"),
                            new ZPair(200, "fann_get_quickprop_decay"),
                            new ZPair(201, "fann_get_quickprop_mu"),
                            new ZPair(202, "fann_get_rprop_decrease_factor"),
                            new ZPair(203, "fann_get_rprop_delta_max"),
                            new ZPair(204, "fann_get_rprop_delta_min"),
                            new ZPair(205, "fann_get_rprop_delta_zero"),
                            new ZPair(206, "fann_get_rprop_increase_factor"),
                            new ZPair(207, "fann_get_sarprop_step_error_shift"),
                            new ZPair(208, "fann_get_sarprop_step_error_threshold_factor"),
                            new ZPair(209, "fann_get_sarprop_temperature"),
                            new ZPair(210, "fann_get_sarprop_weight_decay_shift"),
                            new ZPair(211, "fann_get_total_connections"),
                            new ZPair(212, "fann_get_total_neurons"),
                            new ZPair(213, "fann_get_train_error_function"),
                            new ZPair(214, "fann_get_train_stop_function"),
                            new ZPair(215, "fann_get_training_algorithm"),
                            new ZPair(216, "fann_init_weights"),
                            new ZPair(217, "fann_length_train_data"),
                            new ZPair(218, "fann_merge_train_data"),
                            new ZPair(219, "fann_num_input_train_data"),
                            new ZPair(220, "fann_num_output_train_data"),
                            new ZPair(221, "fann_randomize_weights"),
                            new ZPair(222, "fann_read_train_from_file"),
                            new ZPair(223, "fann_reset_errno"),
                            new ZPair(224, "fann_reset_errstr"),
                            new ZPair(225, "fann_run"),
                            new ZPair(226, "fann_save"),
                            new ZPair(227, "fann_save_train"),
                            new ZPair(228, "fann_scale_input"),
                            new ZPair(229, "fann_scale_input_train_data"),
                            new ZPair(230, "fann_scale_output"),
                            new ZPair(231, "fann_scale_output_train_data"),
                            new ZPair(232, "fann_scale_train"),
                            new ZPair(233, "fann_scale_train_data"),
                            new ZPair(234, "fann_set_activation_function"),
                            new ZPair(235, "fann_set_activation_function_hidden"),
                            new ZPair(236, "fann_set_activation_function_layer"),
                            new ZPair(237, "fann_set_activation_function_output"),
                            new ZPair(238, "fann_set_activation_steepness"),
                            new ZPair(239, "fann_set_activation_steepness_hidden"),
                            new ZPair(240, "fann_set_activation_steepness_layer"),
                            new ZPair(241, "fann_set_activation_steepness_output"),
                            new ZPair(242, "fann_set_bit_fail_limit"),
                            new ZPair(243, "fann_set_callback"),
                            new ZPair(244, "fann_set_cascade_activation_functions"),
                            new ZPair(245, "fann_set_cascade_activation_steepnesses"),
                            new ZPair(246, "fann_set_cascade_candidate_change_fraction"),
                            new ZPair(247, "fann_set_cascade_candidate_limit"),
                            new ZPair(248, "fann_set_cascade_candidate_stagnation_epochs"),
                            new ZPair(249, "fann_set_cascade_max_cand_epochs"),
                            new ZPair(250, "fann_set_cascade_max_out_epochs"),
                            new ZPair(251, "fann_set_cascade_min_cand_epochs"),
                            new ZPair(252, "fann_set_cascade_min_out_epochs"),
                            new ZPair(253, "fann_set_cascade_num_candidate_groups"),
                            new ZPair(254, "fann_set_cascade_output_change_fraction"),
                            new ZPair(255, "fann_set_cascade_output_stagnation_epochs"),
                            new ZPair(256, "fann_set_cascade_weight_multiplier"),
                            new ZPair(257, "fann_set_error_log"),
                            new ZPair(258, "fann_set_input_scaling_params"),
                            new ZPair(259, "fann_set_learning_momentum"),
                            new ZPair(260, "fann_set_learning_rate"),
                            new ZPair(261, "fann_set_output_scaling_params"),
                            new ZPair(262, "fann_set_quickprop_decay"),
                            new ZPair(263, "fann_set_quickprop_mu"),
                            new ZPair(264, "fann_set_rprop_decrease_factor"),
                            new ZPair(265, "fann_set_rprop_delta_max"),
                            new ZPair(266, "fann_set_rprop_delta_min"),
                            new ZPair(267, "fann_set_rprop_delta_zero"),
                            new ZPair(268, "fann_set_rprop_increase_factor"),
                            new ZPair(269, "fann_set_sarprop_step_error_shift"),
                            new ZPair(270, "fann_set_sarprop_step_error_threshold_factor"),
                            new ZPair(271, "fann_set_sarprop_temperature"),
                            new ZPair(272, "fann_set_sarprop_weight_decay_shift"),
                            new ZPair(273, "fann_set_scaling_params"),
                            new ZPair(274, "fann_set_train_error_function"),
                            new ZPair(275, "fann_set_train_stop_function"),
                            new ZPair(276, "fann_set_training_algorithm"),
                            new ZPair(277, "fann_set_weight"),
                            new ZPair(278, "fann_set_weight_array"),
                            new ZPair(279, "fann_shuffle_train_data"),
                            new ZPair(280, "fann_subset_train_data"),
                            new ZPair(281, "fann_test"),
                            new ZPair(282, "fann_test_data"),
                            new ZPair(283, "fann_train"),
                            new ZPair(284, "fann_train_epoch"),
                            new ZPair(285, "fann_train_on_data"),
                            new ZPair(286, "fann_train_on_file"),
                            new ZPair(287, "fbsql_connect"),
                            new ZPair(288, "fbsql_db_query"),
                            new ZPair(289, "fbsql_list_dbs"),
                            new ZPair(290, "fbsql_list_fields"),
                            new ZPair(291, "fbsql_list_tables"),
                            new ZPair(292, "fbsql_pconnect"),
                            new ZPair(293, "fbsql_query"),
                            new ZPair(294, "fdf_create"),
                            new ZPair(295, "fdf_open"),
                            new ZPair(296, "fdf_open_string"),
                            new ZPair(297, "finfo::buffer"),
                            new ZPair(298, "finfo_buffer"),
                            new ZPair(299, "finfo_close"),
                            new ZPair(300, "finfo_file"),
                            new ZPair(301, "finfo_open"),
                            new ZPair(302, "finfo_set_flags"),
                            new ZPair(303, "fopen"),
                            new ZPair(304, "fsockopen"),
                            new ZPair(305, "ftp_alloc"),
                            new ZPair(306, "ftp_cdup"),
                            new ZPair(307, "ftp_chdir"),
                            new ZPair(308, "ftp_chmod"),
                            new ZPair(309, "ftp_close"),
                            new ZPair(310, "ftp_connect"),
                            new ZPair(311, "ftp_delete"),
                            new ZPair(312, "ftp_exec"),
                            new ZPair(313, "ftp_fget"),
                            new ZPair(314, "ftp_fput"),
                            new ZPair(315, "ftp_get"),
                            new ZPair(316, "ftp_get_option"),
                            new ZPair(317, "ftp_login"),
                            new ZPair(318, "ftp_mdtm"),
                            new ZPair(319, "ftp_mkdir"),
                            new ZPair(320, "ftp_nb_continue"),
                            new ZPair(321, "ftp_nb_fget"),
                            new ZPair(322, "ftp_nb_fput"),
                            new ZPair(323, "ftp_nb_get"),
                            new ZPair(324, "ftp_nb_put"),
                            new ZPair(325, "ftp_nlist"),
                            new ZPair(326, "ftp_pasv"),
                            new ZPair(327, "ftp_put"),
                            new ZPair(328, "ftp_pwd"),
                            new ZPair(329, "ftp_raw"),
                            new ZPair(330, "ftp_rawlist"),
                            new ZPair(331, "ftp_rename"),
                            new ZPair(332, "ftp_rmdir"),
                            new ZPair(333, "ftp_set_option"),
                            new ZPair(334, "ftp_site"),
                            new ZPair(335, "ftp_size"),
                            new ZPair(336, "ftp_ssl_connect"),
                            new ZPair(337, "ftp_systype"),
                            new ZPair(338, "gnupg_init"),
                            new ZPair(339, "gupnp_context_new"),
                            new ZPair(340, "gupnp_control_point_new"),
                            new ZPair(341, "gupnp_device_info_get_service"),
                            new ZPair(342, "gupnp_root_device_new"),
                            new ZPair(343, "gzopen"),
                            new ZPair(344, "hash_copy"),
                            new ZPair(345, "hash_final"),
                            new ZPair(346, "hash_init"),
                            new ZPair(347, "hash_update"),
                            new ZPair(348, "hash_update_file"),
                            new ZPair(349, "hash_update_stream"),
                            new ZPair(350, "http_get_request_body_stream"),
                            new ZPair(351, "ibase_blob_create"),
                            new ZPair(352, "ibase_blob_open"),
                            new ZPair(353, "ibase_blob_open 1"),
                            new ZPair(354, "ibase_connect"),
                            new ZPair(355, "ibase_pconnect"),
                            new ZPair(356, "ibase_prepare"),
                            new ZPair(357, "ibase_service_attach"),
                            new ZPair(358, "ibase_set_event_handler"),
                            new ZPair(359, "ibase_set_event_handler 1"),
                            new ZPair(360, "ibase_trans"),
                            new ZPair(361, "ifx_connect"),
                            new ZPair(362, "ifx_pconnect"),
                            new ZPair(363, "ifx_prepare"),
                            new ZPair(364, "ifx_query"),
                            new ZPair(365, "imageaffine"),
                            new ZPair(366, "imageconvolution"),
                            new ZPair(367, "imagecreate"),
                            new ZPair(368, "imagecreatefromgd"),
                            new ZPair(369, "imagecreatefromgd2"),
                            new ZPair(370, "imagecreatefromgd2part"),
                            new ZPair(371, "imagecreatefromgif"),
                            new ZPair(372, "imagecreatefromjpeg"),
                            new ZPair(373, "imagecreatefrompng"),
                            new ZPair(374, "imagecreatefromstring"),
                            new ZPair(375, "imagecreatefromwbmp"),
                            new ZPair(376, "imagecreatefromwebp"),
                            new ZPair(377, "imagecreatefromxbm"),
                            new ZPair(378, "imagecreatefromxpm"),
                            new ZPair(379, "imagecreatetruecolor"),
                            new ZPair(380, "imagegrabscreen"),
                            new ZPair(381, "imagegrabwindow"),
                            new ZPair(382, "imagepalettetotruecolor"),
                            new ZPair(383, "imagepsloadfont"),
                            new ZPair(384, "imagerotate"),
                            new ZPair(385, "imagescale"),
                            new ZPair(386, "imap_open"),
                            new ZPair(387, "inflate_init"),
                            new ZPair(388, "ingres_connect"),
                            new ZPair(389, "ingres_pconnect"),
                            new ZPair(390, "inotify_init"),
                            new ZPair(391, "kadm5_init_with_password"),
                            new ZPair(392, "ldap_connect"),
                            new ZPair(393, "ldap_first_entry"),
                            new ZPair(394, "ldap_first_reference"),
                            new ZPair(395, "ldap_list"),
                            new ZPair(396, "ldap_next_entry"),
                            new ZPair(397, "ldap_next_reference"),
                            new ZPair(398, "ldap_read"),
                            new ZPair(399, "ldap_search"),
                            new ZPair(400, "m_initconn"),
                            new ZPair(401, "mailparse_msg_create"),
                            new ZPair(402, "mailparse_msg_get_part"),
                            new ZPair(403, "mailparse_msg_parse_file"),
                            new ZPair(404, "maxdb::use_result"),
                            new ZPair(405, "maxdb_connect"),
                            new ZPair(406, "maxdb_embedded_connect"),
                            new ZPair(407, "maxdb_init"),
                            new ZPair(408, "maxdb_stmt::result_metadata"),
                            new ZPair(409, "maxdb_stmt_result_metadata"),
                            new ZPair(410, "maxdb_use_result"),
                            new ZPair(411, "mcrypt_module_open"),
                            new ZPair(412, "msg_get_queue"),
                            new ZPair(413, "msql_connect"),
                            new ZPair(414, "msql_db_query"),
                            new ZPair(415, "msql_list_dbs"),
                            new ZPair(416, "msql_list_fields"),
                            new ZPair(417, "msql_list_tables"),
                            new ZPair(418, "msql_pconnect"),
                            new ZPair(419, "msql_query"),
                            new ZPair(420, "mssql_connect"),
                            new ZPair(421, "mssql_init"),
                            new ZPair(422, "mssql_pconnect"),
                            new ZPair(423, "mysql_connect"),
                            new ZPair(424, "mysql_db_query"),
                            new ZPair(425, "mysql_list_dbs"),
                            new ZPair(426, "mysql_list_fields"),
                            new ZPair(427, "mysql_list_processes"),
                            new ZPair(428, "mysql_list_tables"),
                            new ZPair(429, "mysql_pconnect"),
                            new ZPair(430, "mysql_query"),
                            new ZPair(431, "mysql_unbuffered_query"),
                            new ZPair(432, "mysqlnd_uh_convert_to_mysqlnd"),
                            new ZPair(433, "ncurses_new_panel"),
                            new ZPair(434, "ncurses_newpad"),
                            new ZPair(435, "ncurses_newwin"),
                            new ZPair(436, "ncurses_panel_above"),
                            new ZPair(437, "ncurses_panel_below"),
                            new ZPair(438, "ncurses_panel_window"),
                            new ZPair(439, "newt_button"),
                            new ZPair(440, "newt_button_bar"),
                            new ZPair(441, "newt_checkbox"),
                            new ZPair(442, "newt_checkbox_tree"),
                            new ZPair(443, "newt_checkbox_tree_multi"),
                            new ZPair(444, "newt_compact_button"),
                            new ZPair(445, "newt_create_grid"),
                            new ZPair(446, "newt_entry"),
                            new ZPair(447, "newt_form"),
                            new ZPair(448, "newt_form_get_current"),
                            new ZPair(449, "newt_grid_basic_window"),
                            new ZPair(450, "newt_grid_h_close_stacked"),
                            new ZPair(451, "newt_grid_h_stacked"),
                            new ZPair(452, "newt_grid_simple_window"),
                            new ZPair(453, "newt_grid_v_close_stacked"),
                            new ZPair(454, "newt_grid_v_stacked"),
                            new ZPair(455, "newt_label"),
                            new ZPair(456, "newt_listbox"),
                            new ZPair(457, "newt_listitem"),
                            new ZPair(458, "newt_radio_get_current"),
                            new ZPair(459, "newt_radiobutton"),
                            new ZPair(460, "newt_run_form"),
                            new ZPair(461, "newt_scale"),
                            new ZPair(462, "newt_textbox"),
                            new ZPair(463, "newt_textbox_reflowed"),
                            new ZPair(464, "newt_vertical_scrollbar"),
                            new ZPair(465, "oci_connect"),
                            new ZPair(466, "oci_get_implicit_resultset"),
                            new ZPair(467, "oci_new_connect"),
                            new ZPair(468, "oci_new_cursor"),
                            new ZPair(469, "oci_parse"),
                            new ZPair(470, "oci_pconnect"),
                            new ZPair(471, "odbc_columnprivileges"),
                            new ZPair(472, "odbc_columns"),
                            new ZPair(473, "odbc_connect"),
                            new ZPair(474, "odbc_exec"),
                            new ZPair(475, "odbc_foreignkeys"),
                            new ZPair(476, "odbc_gettypeinfo"),
                            new ZPair(477, "odbc_pconnect"),
                            new ZPair(478, "odbc_prepare"),
                            new ZPair(479, "odbc_primarykeys"),
                            new ZPair(480, "odbc_procedurecolumns"),
                            new ZPair(481, "odbc_procedures"),
                            new ZPair(482, "odbc_specialcolumns"),
                            new ZPair(483, "odbc_statistics"),
                            new ZPair(484, "odbc_tableprivileges"),
                            new ZPair(485, "odbc_tables"),
                            new ZPair(486, "openal_buffer_create"),
                            new ZPair(487, "openal_context_create"),
                            new ZPair(488, "openal_device_open"),
                            new ZPair(489, "openal_source_create"),
                            new ZPair(490, "openal_stream"),
                            new ZPair(491, "openssl_csr_new"),
                            new ZPair(492, "openssl_csr_sign"),
                            new ZPair(493, "openssl_pkey_get_private"),
                            new ZPair(494, "openssl_pkey_get_public"),
                            new ZPair(495, "openssl_pkey_new"),
                            new ZPair(496, "openssl_x509_read"),
                            new ZPair(497, "pfsockopen"),
                            new ZPair(498, "pg_cancel_query"),
                            new ZPair(499, "pg_client_encoding"),
                            new ZPair(500, "pg_close"),
                            new ZPair(501, "pg_connect"),
                            new ZPair(502, "pg_connect_poll"),
                            new ZPair(503, "pg_connection_busy"),
                            new ZPair(504, "pg_connection_reset"),
                            new ZPair(505, "pg_connection_status"),
                            new ZPair(506, "pg_consume_input"),
                            new ZPair(507, "pg_copy_from"),
                            new ZPair(508, "pg_copy_to"),
                            new ZPair(509, "pg_dbname"),
                            new ZPair(510, "pg_end_copy"),
                            new ZPair(511, "pg_escape_bytea"),
                            new ZPair(512, "pg_escape_identifier"),
                            new ZPair(513, "pg_escape_identifier 1"),
                            new ZPair(514, "pg_escape_literal"),
                            new ZPair(515, "pg_escape_string"),
                            new ZPair(516, "pg_execute"),
                            new ZPair(517, "pg_execute 1"),
                            new ZPair(518, "pg_flush"),
                            new ZPair(519, "pg_free_result"),
                            new ZPair(520, "pg_get_notify"),
                            new ZPair(521, "pg_get_pid"),
                            new ZPair(522, "pg_get_result"),
                            new ZPair(523, "pg_host"),
                            new ZPair(524, "pg_last_error"),
                            new ZPair(525, "pg_last_notice"),
                            new ZPair(526, "pg_lo_create"),
                            new ZPair(527, "pg_lo_export"),
                            new ZPair(528, "pg_lo_import"),
                            new ZPair(529, "pg_lo_open"),
                            new ZPair(530, "pg_lo_unlink"),
                            new ZPair(531, "pg_options"),
                            new ZPair(532, "pg_parameter_status"),
                            new ZPair(533, "pg_pconnect"),
                            new ZPair(534, "pg_ping"),
                            new ZPair(535, "pg_port"),
                            new ZPair(536, "pg_prepare"),
                            new ZPair(537, "pg_prepare 1"),
                            new ZPair(538, "pg_put_line"),
                            new ZPair(539, "pg_query"),
                            new ZPair(540, "pg_query 1"),
                            new ZPair(541, "pg_query_params"),
                            new ZPair(542, "pg_query_params 1"),
                            new ZPair(543, "pg_send_execute"),
                            new ZPair(544, "pg_send_prepare"),
                            new ZPair(545, "pg_send_query"),
                            new ZPair(546, "pg_send_query_params"),
                            new ZPair(547, "pg_set_client_encoding"),
                            new ZPair(548, "pg_set_client_encoding 1"),
                            new ZPair(549, "pg_set_error_verbosity"),
                            new ZPair(550, "pg_socket"),
                            new ZPair(551, "pg_trace"),
                            new ZPair(552, "pg_transaction_status"),
                            new ZPair(553, "pg_tty"),
                            new ZPair(554, "pg_untrace"),
                            new ZPair(555, "pg_version"),
                            new ZPair(556, "php_user_filter::filter"),
                            new ZPair(557, "popen"),
                            new ZPair(558, "proc_open"),
                            new ZPair(559, "ps_new"),
                            new ZPair(560, "px_new"),
                            new ZPair(561, "radius_acct_open"),
                            new ZPair(562, "radius_auth_open"),
                            new ZPair(563, "radius_salt_encrypt_attr"),
                            new ZPair(564, "rpm_open"),
                            new ZPair(565, "sem_get"),
                            new ZPair(566, "shm_attach"),
                            new ZPair(567, "socket_accept"),
                            new ZPair(568, "socket_create"),
                            new ZPair(569, "socket_create_listen"),
                            new ZPair(570, "socket_recvmsg"),
                            new ZPair(571, "socket_sendmsg"),
                            new ZPair(572, "sqlite_open"),
                            new ZPair(573, "sqlite_popen"),
                            new ZPair(574, "sqlsrv_begin_transaction"),
                            new ZPair(575, "sqlsrv_cancel"),
                            new ZPair(576, "sqlsrv_client_info"),
                            new ZPair(577, "sqlsrv_close"),
                            new ZPair(578, "sqlsrv_commit"),
                            new ZPair(579, "sqlsrv_connect"),
                            new ZPair(580, "sqlsrv_execute"),
                            new ZPair(581, "sqlsrv_fetch"),
                            new ZPair(582, "sqlsrv_fetch_array"),
                            new ZPair(583, "sqlsrv_fetch_object"),
                            new ZPair(584, "sqlsrv_field_metadata"),
                            new ZPair(585, "sqlsrv_free_stmt"),
                            new ZPair(586, "sqlsrv_get_field"),
                            new ZPair(587, "sqlsrv_has_rows"),
                            new ZPair(588, "sqlsrv_next_result"),
                            new ZPair(589, "sqlsrv_num_fields"),
                            new ZPair(590, "sqlsrv_num_rows"),
                            new ZPair(591, "sqlsrv_prepare"),
                            new ZPair(592, "sqlsrv_query"),
                            new ZPair(593, "sqlsrv_rollback"),
                            new ZPair(594, "sqlsrv_rows_affected"),
                            new ZPair(595, "sqlsrv_send_stream_data"),
                            new ZPair(596, "sqlsrv_server_info"),
                            new ZPair(597, "ssh2_auth_agent"),
                            new ZPair(598, "ssh2_connect"),
                            new ZPair(599, "ssh2_exec"),
                            new ZPair(600, "ssh2_fetch_stream"),
                            new ZPair(601, "ssh2_publickey_init"),
                            new ZPair(602, "ssh2_sftp"),
                            new ZPair(603, "ssh2_sftp_chmod"),
                            new ZPair(604, "ssh2_shell"),
                            new ZPair(605, "ssh2_tunnel"),
                            new ZPair(606, "stomp_connect"),
                            new ZPair(607, "streamWrapper::stream_cast"),
                            new ZPair(608, "stream_bucket_new"),
                            new ZPair(609, "stream_context_create"),
                            new ZPair(610, "stream_context_get_default"),
                            new ZPair(611, "stream_context_set_default"),
                            new ZPair(612, "stream_filter_append"),
                            new ZPair(613, "stream_filter_prepend"),
                            new ZPair(614, "stream_socket_accept"),
                            new ZPair(615, "stream_socket_client"),
                            new ZPair(616, "stream_socket_server"),
                            new ZPair(617, "svn_fs_apply_text"),
                            new ZPair(618, "svn_fs_begin_txn2"),
                            new ZPair(619, "svn_fs_file_contents"),
                            new ZPair(620, "svn_fs_revision_root"),
                            new ZPair(621, "svn_fs_txn_root"),
                            new ZPair(622, "svn_repos_create"),
                            new ZPair(623, "svn_repos_fs"),
                            new ZPair(624, "svn_repos_fs_begin_txn_for_commit"),
                            new ZPair(625, "svn_repos_open"),
                            new ZPair(626, "sybase_connect"),
                            new ZPair(627, "sybase_pconnect"),
                            new ZPair(628, "sybase_unbuffered_query"),
                            new ZPair(629, "tmpfile"),
                            new ZPair(630, "udm_alloc_agent"),
                            new ZPair(631, "udm_alloc_agent_array"),
                            new ZPair(632, "udm_find"),
                            new ZPair(633, "unlink"),
                            new ZPair(634, "w32api_init_dtype"),
                            new ZPair(635, "wddx_packet_start"),
                            new ZPair(636, "xml_parser_create"),
                            new ZPair(637, "xml_parser_create_ns"),
                            new ZPair(638, "xml_parser_free"),
                            new ZPair(639, "xml_parser_get_option"),
                            new ZPair(640, "xml_parser_set_option"),
                            new ZPair(641, "xmlrpc_server_create"),
                            new ZPair(642, "xmlwriter_open_memory"),
                            new ZPair(643, "xmlwriter_open_uri"),
                            new ZPair(644, "xslt_create"),
                            new ZPair(645, "zip_open"),
                            new ZPair(646, "zip_read")));
        }
    }

    public static final RuntimeStaticCompanion runtimeStaticObject = new RuntimeStaticCompanion();

    private static final ReflectionClassData runtimeConverterReflectionData =
            ReflectionClassData.builder()
                    .setName("SebastianBergmann\\ResourceOperations\\ResourceOperations")
                    .setLookup(ResourceOperations.class, java.lang.invoke.MethodHandles.lookup())
                    .setLocalProperties()
                    .setFilename("vendor/sebastian/resource-operations/src/ResourceOperations.php")
                    .get();

    @Override
    public ReflectionClassData getRuntimeConverterReflectionData() {
        return runtimeConverterReflectionData;
    }

    @Override
    public Object converterRuntimeCallExtended(
            RuntimeEnv env,
            String method,
            Class<?> caller,
            PassByReferenceArgs passByReferenceArgs,
            Object... args) {
        return RuntimeClassBase.converterRuntimeCallExtendedWithDataStatic(
                this,
                runtimeConverterReflectionData,
                env,
                method,
                caller,
                passByReferenceArgs,
                args);
    }
}
